import { Router } from 'express';
import { branchesRouter } from '@/modules/branches/branches.routes';
import { departmentsRouter } from '@/modules/departments/departments.routes';
import { positionsRouter } from '@/modules/positions/positions.routes';
import { levelsRouter } from '@/modules/levels/levels.routes';
import { shiftsRouter } from '@/modules/shifts/shifts.routes';
import { employeesRouter } from '@/modules/employees/employees.routes';
import { schedulesRouter } from '@/modules/schedules/schedules.routes';
import { attendanceRouter } from '@/modules/attendance/attendance.routes';
import { newsRouter } from '@/modules/news/news.routes';
import { notificationsRouter } from '@/modules/notifications/notifications.routes';
import { uploadsRouter } from '@/modules/uploads/uploads.routes';
import { evaluationsRouter } from '@/modules/evaluations/evaluations.routes';
import { evaluationCriteriaRouter } from '@/modules/evaluation-criteria/evaluation-criteria.routes';
import { trainingCriteriaRouter } from '@/modules/training-criteria/training-criteria.routes';
import { trainingLogsRouter } from '@/modules/training-logs/training-logs.routes';
import { workReviewSectionsRouter } from '@/modules/work-review-sections/work-review-sections.routes';
import { workReviewsRouter } from '@/modules/work-reviews/work-reviews.routes';

export const apiRouter = Router();

apiRouter.use('/branches', branchesRouter);
apiRouter.use('/departments', departmentsRouter);
apiRouter.use('/positions', positionsRouter);
apiRouter.use('/levels', levelsRouter);
apiRouter.use('/shifts', shiftsRouter);
apiRouter.use('/employees', employeesRouter);
apiRouter.use('/schedules', schedulesRouter);
apiRouter.use('/attendance', attendanceRouter);
apiRouter.use('/news', newsRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/uploads', uploadsRouter);
apiRouter.use('/evaluations', evaluationsRouter);
apiRouter.use('/evaluation-criteria', evaluationCriteriaRouter);
apiRouter.use('/training-criteria', trainingCriteriaRouter);
apiRouter.use('/training-logs', trainingLogsRouter);
apiRouter.use('/work-review-sections', workReviewSectionsRouter);
apiRouter.use('/work-reviews', workReviewsRouter);
